# Logistic Regression

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss

%matplotlib inline 

import warnings
warnings.filterwarnings('ignore')

## Classification with Logistic Regression

### Scenario
Assume that you are working for a telecommunications company which is concerned about the number of customers leaving their land-line business for cable competitors. They need to understand who is more likely to leave the company.

###  Load the Telco Churn data 
Telco Churn is a hypothetical data file that concerns a telecommunications company's efforts to reduce turnover in its customer base. Each case corresponds to a separate customer and it records various demographic and service usage information. Before you can work with the data, you must use the URL to get the ChurnData.csv.


### About the dataset
We will use a telecommunications dataset for predicting customer churn. This is a historical customer dataset where each row represents one customer. The data is relatively easy to understand, and you may uncover insights you can use immediately. Typically it is less expensive to keep customers than acquire new ones, so the focus of this analysis is to predict the customers who will stay with the company. 
<br><br>
This data set provides you information about customer preferences, services opted, personal details, etc. which helps you predict customer churn.


In [29]:
# churn_df = pd.read_csv("ChurnData.csv")
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv"

churn_df = pd.read_csv(url)
churn_df

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [5]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip','churn']]
churn_df['churn'] = churn_df['churn'].astype('int')
churn_df

tenure   age  address  income   ed  employ  equip  churn
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0      1
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0      1
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0      0
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0      0
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0      0
..      ...   ...      ...     ...  ...     ...    ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0      0
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0      0
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0      0
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0      1
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0      0

[200 rows x 8 columns]

In [16]:
X = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5]  #print the first 5 values

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [ ]:
y = np.asarray(churn_df['churn'])
y[0:5] #print the first 5 values

In [20]:
X = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']]
y = churn_df['churn']

print(X[0:5])
print('------')
print(y[0:5])

   tenure   age  address  income   ed  employ  equip
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0
------
0    1
1    1
2    0
3    0
4    0
Name: churn, dtype: int64


It is also a norm to standardize or normalize the dataset in order to have all the features at the same scale. This helps the model learn faster and improves the model performance. We may make use of StandardScalar function in the Scikit-Learn library.


In [21]:
X_norm = StandardScaler().fit(X).transform(X)
X_norm

array([[-1.13518441, -0.62595491, -0.4588971 , ...,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, ..., -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , ..., -1.42318853,
        -0.92053635, -0.85972695],
       ...,
       [-1.36680743, -0.7026181 , -0.16283445, ..., -1.42318853,
        -0.02518185, -0.85972695],
       [-0.53296457, -0.85594447, -1.14970993, ...,  0.91629947,
        -0.58477841, -0.85972695],
       [ 1.18104577,  0.67731925,  0.42929083, ..., -0.6433592 ,
         1.31784991,  1.16316   ]], shape=(200, 7))

# Splitting the Dataset 
The trained model has to be tested and evaluated on data which has not been used during training. Therefore, it is required to separate a part of the data for testing and the remaining for training. For this, we may make use of the train_test_split function in the scikit-learn library.


In [34]:
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.2, random_state=4)

# Logistic Regression Classifier modeling
Let's build the model using __LogisticRegression__ from the Scikit-learn package and fit our model with train data set.



In [35]:
LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [36]:
prediction = LR.predict(X_test)
prediction[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

To understand this prediction, we can also have a look at the prediction probability of data point of the test data set. Use the function __predict_proba__ , we can get the probability of each class. The first column is the probability of the record belonging to class 0, and second column that of class 1. Note that the class prediction system uses the threshold for class prediction as 0.5. This means that the class predicted is the one which is most likely.


In [37]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob[:10]

array([[0.74643946, 0.25356054],
       [0.92667894, 0.07332106],
       [0.83442627, 0.16557373],
       [0.94600618, 0.05399382],
       [0.84325532, 0.15674468],
       [0.71448367, 0.28551633],
       [0.77076426, 0.22923574],
       [0.90955642, 0.09044358],
       [0.26152115, 0.73847885],
       [0.94900731, 0.05099269]])

# Performance Evaluation

Once the predictions have been generated, it becomes prudent to evaluate the performance of the model in predicting the target variable. Let us evaluate the log-loss value.

### log loss

Log loss (Logarithmic loss), also known as Binary Cross entropy loss, is a function that generates a loss value based on the class wise prediction probabilities and the actual class labels. The lower the log loss value, the better the model is considered to be.


In [39]:
log_loss(y_test, yhat_prob)

0.6257718410257235

# Practice Q

a. Let us assume we add the feature 'callcard' to the original set of input features. What will the value of log loss be in this case?

In [32]:
churn_df

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [33]:
churn_df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [ ]:
churn_df_p = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip','callcard', 'wireless','churn']]
churn_df_p['churn'] = churn_df_p['churn'].astype('int')
churn_df_p